#!/bin/bash

# Global settings
yabai -m config layout bsp
yabai -m config window_gap 5
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5

# Window behavior
yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_follows_focus off
yabai -m config window_placement second_child
yabai -m config window_shadow off

# Space settings
yabai -m config auto_balance on
yabai -m config split_ratio 0.50

# Disable macOS window animations
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90

